parameters:
- name: kvRgSerCon
  type: string
- name: kvName
  type: string
- name: kvSecretsFilter
  type: string
  default: '*'

steps:
  - task: AzureKeyVault@1
    displayName: 'Load data from key vault [${{ Parameters.kvName }}]'
    inputs:
      azureSubscription: '${{ Parameters.kvRgSerCon }}'
      KeyVaultName: '${{ Parameters.kvName }}'
      SecretsFilter: '${{ Parameters.kvSecretsFilter }}'