trigger: none
pr: none

variables:
- name: branchName 
  value:  $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
- template: /DevOps/variables/build-variables.yml

stages:

- stage: Build
  displayName: Build
  jobs:
  - job: Build_job
    displayName: Build
    pool: $(agents_pool_name)
    steps:
    # Checkout repo
    - checkout: self
      clean: true
    # Load KV
    - template: /DevOps/steps/load-kv-secrets.yml
      parameters:
        kvRgSerCon: '$(azure_service_connection_name)'
        kvName: '$(kv_name)'
    # Use dotnet core 3.1
    - task: UseDotNet@2
      displayName: 'Use .NET Core sdk'
      inputs:
        packageType: sdk
        version: 6.0.x
        installationPath: $(Agent.ToolsDirectory)/dotnet
    # Restore
    - task: DotNetCoreCLI@2
      displayName: 'dotnet restore'
      inputs:
        command: restore
        projects: '$(Build.SourcesDirectory)/IceCreamRatingsApiProject/IceCreamRatingsApiProject.csproj'
    # Build and Publish
    - task: DotNetCoreCLI@2
      displayName: 'dotnet publish'
      inputs:
        command: publish
        publishWebProjects: False
        projects: '$(Build.SourcesDirectory)/IceCreamRatingsApiProject/IceCreamRatingsApiProject.csproj'
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    # Publish artifact    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish zip artifact'
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'functionapp'
    # Deploy artifact
    - task: AzureFunctionApp@1
      displayName: 'Deploy - AzureFunctionApp'
      inputs:
        azureSubscription: '$(azure_service_connection_name)'
        appType: 'functionApp'
        appName: $(funcappname)
        package: '$(Build.ArtifactStagingDirectory)/**/*.zip' # string. Required. Package or folder. Default: $(System.DefaultWorkingDirectory)/**/*.zip.
        #runtimeStack: # 'DOTNET|2.2' | 'DOTNET|3.1' | 'DOTNET|6.0' | 'JAVA|8' | 'JAVA|11' | 'NODE|8' | 'NODE|10' | 'NODE|12' | 'NODE|14' | 'NODE|16' | 'PYTHON|3.6' | 'PYTHON|3.7' | 'PYTHON|3.8' | 'PYTHON|3.9'. Optional. Use when appType = functionAppLinux. Runtime stack. 
        deploymentMethod: 'auto' # 'auto' | 'zipDeploy' | 'runFromPackage'. Required.
        appSettings: '-MSSQL_CONSTR "$(mssql-constr)"'
